-- CREATE DATABASE  IF NOT EXISTS `test`;
-- USE `test`;


-- DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `user3123`;
CREATE TABLE `user3123` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `login` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index2` (`login`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



 LOCK TABLES `user3123` WRITE;
 INSERT INTO `user3123` VALUES (null,'1'),(null,'2'),(null,'3');
 UNLOCK TABLES;